# Service Registration and Discovery

Microservices architecture require a significant amount of investment in `NoOps' or http://blogs.gartner.com/gary-olliffe/2015/01/30/microservices-guts-on-the-outside/[Outer Architecture]. One of the key components of that is service registration and discovery. Multiple microservices are composed to create an application and each microservice can scale independently. Exact location or URI of the service may not be known until its deployed, especially if its deployed in a PaaS or using Containers.

_Service registration_ allows each microservice to register itself with a _registry_ using a logical name. This name is bound to a physical URI obtained from a PaaS or a Container. This logical name can then be used during _service discovery_ to discover the service by the consumers, and then invoke, the microservice. If the microservice goes down then the consumers are notified accordingly. The logical name allows the physical URI to change if the microservice is started on a different ``node'' on PaaS or a Container. The logical name also allows to register multiple physical URIs, and thus load balance, possibly metrics-driven, to distribute the requests amongst multiple microservices.

There are multiple tools used for service registry and discovery. This document will highlight how to use them from a Java application.

## ZooKeeper

Curator

. Start ZooKeeper container
+
[source, text]
----
docker run -it -p 2181:2181 jplock/zookeeper
----
+
.

. Written in Java
. CP from CAP


## Consul

consul-registrar, consul-template

. Written in Go
. AP from CAP

## etcd

https://github.com/jurmous/etcd4j

## Kubernetes

## Eureka
