INSERT INTO ItemType("ID", "NAME") VALUES (1, 'Book')
INSERT INTO ItemType("ID", "NAME") VALUES (2, 'Jewelry')
INSERT INTO ItemType("ID", "NAME") VALUES (3, 'Shoes')
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (1, 'Minecraft Modding with Forge', 1)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (2, 'Java EE 7 Essentials', 1)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (3, 'Java EE 6 Pocket Guide', 1)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (4, 'Java EE 7 & HTML5 Enterprise Application Development', 1)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (5, 'Wedding Band', 2)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (6, 'Bangles', 2)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (7, 'Necklace', 2)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (8, 'Earrings', 2)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (9, 'Mizuno Wave Sayonara', 3)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (10, 'Nike Free 5.0', 3)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (11, 'Salomon Men''s Quest 4D', 3)
INSERT INTO Item("ID", "NAME", "TYPE") VALUES (12, 'New Balance Minimus', 3)
