INSERT INTO CatalogItemType("ID", "NAME") VALUES (1, 'Book')
INSERT INTO CatalogItemType("ID", "NAME") VALUES (2, 'Jewelry')
INSERT INTO CatalogItemType("ID", "NAME") VALUES (3, 'Shoes')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (1, 'Minecraft Modding with Forge', 1, 'Book - Minecraft Modding with Forge')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (2, 'Java EE 7 Essentials', 1, 'Book - Java EE 7 Essentials')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (3, 'Java EE 6 Pocket Guide', 1, 'Book - Java EE 6 Pocket Guide')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (4, 'Java EE 7 & HTML5 Enterprise Application Development', 1, 'Book - Java EE 7 & HTML5 Enterprise Application Development')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (5, 'Wedding Band', 2, 'Jewelry - Wedding Band')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (6, 'Bangles', 2, 'Jewelry - Bangles')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (7, 'Necklace', 2, 'Jewelry - Necklace')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (8, 'Earrings', 2, 'Jewelry - Earrings')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (9, 'Mizuno Wave Sayonara', 3, 'Shoes - Mizuno Wave Sayonara')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (10, 'Nike Free 5.0', 3, 'Shoes - Nike Free 5.0')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (11, 'Salomon Men''s Quest 4D', 3, 'Shoes - Salomon Men''s Quest 4D')
INSERT INTO CatalogItem("ID", "NAME", "TYPE", "DESCRIPTION") VALUES (12, 'New Balance Minimus', 3, 'Shoes - New Balance Minimus')
